my_string= input('Есть только ')
print('У самурая нет цели, есть только',my_string)
print(len('У самурая нет цели, есть только')+len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(my_string[-1])